Geo-Web-Project/cadastre

components/gallery/GalleryForm.js
components/gallery/GalleryModal.js

Adds functionality to manually select a file format when adding an existing CID.

Manually select file format on adding existing IPFS object

---

lib/GeoWebBucket.ts

Fixes #169 
This fixes what appears to be a regression in pinning logic. There are still improvements to make to improve pinning performance. I have some ideas, but for now this PR should restore the performance to what it was in the previous testnet.

fix: Media Gallery pins are failing 

---

components/InfoTooltip.tsx
components/cards/TransactionSummaryView.tsx

This will add tooltips to the transaction summary field values in `components/cards/TransactionSummaryView.tsx`
closes #189 
This builds off of the work on this PR -> #195 I will update the branch once that PR has been merged.

Adding tooltips to the transaction summary field values

---

components/cards/ActionForm.tsx
components/cards/OutstandingBidView.tsx
components/cards/PlaceBidAction.tsx
components/cards/RejectBidAction.tsx
components/cards/TransactionError.tsx

This PR aims to fix the issue #205 by adding:
- Custom error messages on transaction modals
- Removing the close icon as it is not possible right now with different bootstrap and react-bootstrap versions
- Capitalize error message
- Creating a custom modal for TransactionError

fix: Update transaction error modal for a custom message

---

components/Map.tsx

Closes #201 
- Removed `renderWorldCopies` prop because the default value is necessary to have the globe panning work properly
- Removed some redundant code that should have been removed in #202

Change the Cadastre to a globe projection

---

pages/index.tsx
redux/store.ts

We are using the default ethers.js provider, which has a low rate limit, because the environment variable passed to the function returning the provider is not defined in the `.env` file.
Passing the correct environment variable gives us a provider with higher rate limit.
fixes #227 

fix: use correct API key to get Infura provider

---

components/Map.tsx

Replace `lastBlock` with `lastId` in gql query to properly paginate through coordinates, allowing larger parcels to fully load.
fixes #223 
related to https://github.com/Geo-Web-Project/cadastre/pull/256 

fix: paginate coords using ID in place of createdAtBlock

---

lib/constants.ts

Update the block explorer link to point to the right network (Goerli)
Changes the `BLOCK_EXPLORER` value to the Goerli Etherscan link
N/A
@codynhat

fix: update block explorer to Goerli Etherscan

---

components/cards/ParcelInfo.tsx
components/cards/ReclaimAction.tsx

Maintain the parcel content when a licensor reclaims their parcel.
fixes #262 

fix: conserve parcel content on reclaim

---

components/ApproveButton.tsx
components/cards/ActionForm.tsx
components/cards/OutstandingBidView.tsx
components/cards/PlaceBidAction.tsx
components/cards/RejectBidAction.tsx

Ignore the error raised when a transaction is successfully repriced.
fixes #281
When a transaction is repriced Ethers.js raises the `TRANSACTION_REPLACED` error, sets `cancelled` of the error object to `false` and execution after `txn.wait()` continue, in all other cases (like when a transaction is replaced by another unrelated transaction) `error.cancelled` is set to `true` and we error out.

fix: ignore transaction repriced error

---

components/cards/ClaimInfo.tsx

Update the Claim Info window to describe the maximum claim dimensions (200 coordinates tall and/or wide)
N/A
Updating Cadastre to reflect requirements implemented in https://github.com/Geo-Web-Project/core-contracts/pull/105
@codynhat

feat: add max claim dimensions line to claim info

---

components/gallery/GalleryDisplayGrid.tsx
components/gallery/GalleryDisplayItem.tsx
components/gallery/GalleryModal.tsx

When the user remove an item from the media gallery update the grid so that it reflect the change.
fixes #295 

fix: update media gallery on removed item

---

components/Map.tsx

For the case of the user jumpimg to a parcel from the portfolio modal remove the offset from the coordinates to be passed as query params to the spatial browser and add it to the ones passed to `flyToLocation()` so that the parcel is centered.
fixes #300 

fix: use coordinates without offset for spatial browser query params

---

components/profile/ProfileModal.tsx

Double the Buffer Deposit value shown in the ProfileModal's table. 
fixes #293 

fix: double the buffer deposit value in ProfileModal

---

components/Map.tsx
lib/constants.ts
pages/_app.tsx

Use `createdAtBlock` field of `geoWebParcel` in the subgraph for pagination.
fixes #285 

fix: use createdAtBlock field for pagination

---

components/Map.tsx

Change `QUERY_DIM` so that a refetch of parcels is triggered when the user pan around the map.
The value should be low enough to not miss parcels and high enough to avoid redundant refetches.
fixes #306 

fix: trigger parcels refetch on move

---

components/Home.tsx
pages/index.tsx

In the landing page set the height of the container to take at least the whole height available so that the background covers the whole screen on desktop monitors.

fix: use whole screen height for landing page background

---

components/cards/ActionForm.tsx

Use `requiredBid` to validate `displayNewForSalePrice` in reclaim/foreclosure auction contexts unless it is less than `minForSalePrice`.
fixes #320 

fix: use required bid for price validation in foreclosure auctions

---

components/cards/PlaceBidAction.tsx

When the user wants to place a bid calculate the *Stream Buffer* based on the full value of the bidder's *For Sale Price* instead of subtracting the `existingNetworkFee` (in `TransactionSummary` component `existingNetworkFee` is initialised to 0 when not passed as a prop by `PlaceBidAction` and nothing is subtracted from `newBuffer` during `streamBuffer` calculation).
fixes #321 

fix: calculate stream buffer for place bid actions without the existing network fee

---

components/cards/ActionForm.tsx

Set `requiredFlowAmount` to 0 if during edit actions the user doesn't change the parcel price so that a transaction only for content changes can be submitted without the approval flow.
fixes #325 

fix: set required flow amount to zero if there is no price change in edit actions

---

components/profile/ProfileModal.tsx

Catch Ceramic errors in `ProfileModal` so that the ID of the interested parcel is logged with the error message and a fallback name is used instead of the name that wasn't possible to retrieve.
fixes #327

fix: catch Ceramic errors in profile modal

---

components/cards/ParcelInfo.tsx

Switch the order of the latitude and longitude variables used in the "Open in Spatial Browser" link to follow conventional ordering.
N/A

feat: switch the order of lat/long in the browser link

---

components/cards/ActionForm.tsx
components/cards/ParcelInfo.tsx
components/gallery/GalleryForm.tsx
components/gallery/GalleryModal.tsx
lib/geo-web-content/mediaGallery.ts
package.json

Check if there was an initialisation failure by checking if the `@geo-web/content` library method `resolveRoot` returns an empty object and if so show a "Not Available" message instead of the Root CID in the parcel info panel.
If there was an initialisation failure the media gallery must be initialised before adding content, this is done in the `useMediaGallery` custom hook.
fixes #339 

fix: handle parcel content initialization failure

---

.env.testnet
components/Map.tsx

Show a view of the whole earth on map load.
fixes #347 
- Set `interactiveLayerIds` after the map loads and the grid is calculated.

feat: show globe view on map load

---

components/FairLaunchHeader.tsx

Avoid the text showing the current bid in the fair launch header to wrap around on small screens.
fixes #350 

fix: do not allow text to wrap around the header

---

components/cards/ParcelInfo.tsx
lib/geo-web-content/basicProfile.ts

When an update of `parcelContent` fails because there isn't yet a root CID associated with the parcel and owner the update flag is cleared so that we can retry when the root CID is present. 
fixes #353 

fix: clear update flag on content retrieval error

---

.env.mainnet
.env.testnet
components/cards/ActionForm.tsx
components/gallery/GalleryDisplayItem.tsx
components/gallery/GalleryForm.tsx
lib/geo-web-content/mediaGallery.ts
package.json
pages/index.tsx
yarn.lock

Pins only the new nodes along a branch on `putPath`. Also updates `@geo-web/content` to not download entire CAR on `getPath`.
closes #356

perf: Upload DAG branch only on putPath

---

components/Map.tsx
components/gallery/GalleryForm.tsx
pages/index.tsx

Fixes an issue where actual media gallery item content is not being pinned to Web3.storage.
`js-geo-web` only pins the DAG, and not the `content` field of a media object. This updates the Cadastre to pin the content separately.

fix: Upload media object content to Web3.storage

---

components/Sidebar.tsx
components/cards/ParcelInfo.tsx
lib/geo-web-content/basicProfile.ts

Pass a `key` prop to `ParcelInfo` to tell react to render a different component every time `selectedParcelId` change instead of rerender the same component with different props and same state, otherwise when the user change the selected parcel the custom hook that returns the parcel content is not triggered until the license owner address is fetched from the subgraph, causing the parcel info panel to show stale data until `parcelContent` is updated.
fixes #364 
Wait for `useBasicProfile` to return before showing the parcel name to avoid briefly displaying the fallback info instead of the name when a basic profile is present.

fix: render a different ParcelInfo for every parcel

---

components/gallery/GalleryFileFormat.ts
components/gallery/GalleryForm.tsx
components/gallery/GalleryModal.tsx

Update the text in the gallery modal to specify the file types currently supported by the Geo Web Spatial Browser.
Only allow uploads of .glb and .usdz files but allow already uploaded media objects to be edited even if their content is not a 3D model.
fixes #365 

feat: specify current spatial browser supported file types in the media gallery modal

---

components/CopyTokenAddress.tsx
components/CopyTooltip.tsx
components/profile/ProfileModal.tsx
components/wrap/WrapModal.tsx

Add validation to `WrapModal` and the two wrap and unwrap forms in `ProfileModal`.
- Disable the submit button if the user is out of balance.
- Show a warning message if the amount of ETH that would remain after a wrapping transaction is less than 0.001 ETH.
- Show an error message if there is some error during the transaction.
- Truncate the wallet balances in the `ProfileModal` to 8 digits.
- Make the elements more responsive to smaller screen sizes.
fixes #370 

feat: add validation to wrapping and unwrapping flow

---

components/profile/ProfileModal.tsx

Show a loading spinner while fetching portfolio parcels data in `ProfileModal`.
fixes #376 

feat: show loading spinner in profile dashboard

---

pages/index.tsx

On mobile screens hide the *Connect Wallet* button and the *Cadastre Beta* text in the header.
fixes #377 

feat: hide wallet connect button and text next to logo on mobile

---

components/cards/ActionForm.tsx
components/cards/ParcelInfo.tsx
lib/geo-web-content/basicProfile.ts

Set the root CID inside the custom hook used to get `parcelContent` instead of the effect hook in `ParceInfo`, so that both the basic profile info and the root CID are showed at the same time in the UI.
fixes #382 

fix: set root cid inside basic profile custom hook

---

components/ConnectWallet.tsx

Removes using cookies from SSX for better reliability and Safari support. The SIWE message is now set directly on `/delegation`
@tnrdd

fix: Remove using cookies on delegation

---

components/ApproveButton.tsx
components/cards/ActionForm.tsx
components/cards/ClaimAction.tsx
components/cards/EditAction.tsx
components/cards/OutstandingBidView.tsx
components/cards/ParcelInfo.tsx
components/cards/PlaceBidAction.tsx
components/cards/ReclaimAction.tsx
components/cards/RejectBidAction.tsx

- Update *For Sale Price* and *License Owner* fields on successful parcel transfer so that the the UI shows the correct info before we switch state.
- Update the *License Owner* field after the IPFS content on claim, edit and reclaim transactions to avoid the UI showing wrong info for a bit.
- While a transaction is being confirmed keep the approve button in its latest state (ETHx use allowed).
fixes #421 

fix: ensure correct info is shown during state transition

---

components/Map.tsx
components/OffCanvasPanel.tsx
components/cards/ParcelInfo.tsx
components/cards/StreamingInfo.tsx
components/parcels/Foreclosure.tsx
components/parcels/HighestValue.tsx
components/parcels/NeedsTransfer.tsx
components/parcels/OutstandingBid.tsx
components/parcels/ParcelList.tsx
components/parcels/Random.tsx
components/parcels/Recent.tsx
components/profile/Profile.tsx
components/profile/ProfileModal.tsx
lib/parcelNavigation.ts
pages/_app.tsx
pages/index.tsx

Navigate to a parcel from an URL using only the parcel ID without the coordinates.
fixes #408 
The `useParcelNavigation` custom hook takes an optional `parcelId` argument and returns some functions used to resolve the ID to GPS coordinates and to navigate to the parcel.
This replaces the current way to do parcel navigation from the modals allowing us to imperatively call Mapbox's `flyTo` from the event handler and avoid some rerender caused by `setState` and `useEffect`.

feat: use only ID for URL based parcel navigation

---

components/InfoTooltip.tsx
components/cards/ActionForm.tsx
components/cards/ClaimAction.tsx

Add tooltips to *Parcel Name* and *Content Link* input labels.
fixes #409 
- [x ] My PR is rebased off the most recent `develop` branch

feat: add tooltips to parcel name and content link input labels

---

components/Map.tsx
components/cards/ActionForm.tsx
components/cards/PlaceBidAction.tsx
components/cards/RejectBidAction.tsx

Prevent balance and claim size/position validation after the claim is already made and before switching to the new parcel view.
fixes #430 

fix: do not validate balance and claim size during transaction processing

---

pages/_app.tsx

Memoize the `ApolloClient` instance so that when `/pages/_app.tsx` re-render after `setAuthStatus` we continue using the first client instead of assign a new one and lose the cached data.
fixes #434 

fix: memoize graphQL client

---

components/NotificationModal.tsx
components/cards/ParcelInfo.tsx

Reduce the size of the icons in the parcel info view.
fixes #439 

fix: reduce icons size in parcel info view

---

src/components/governance/EditStream.tsx

Fixes a bug that caused the second decimal place in the matching pool donation input field to not be allowed to be inserted.

fix(governance): matching pool donation input validation

---

src/components/governance/EditStream.tsx

- Changes the default suggested wrap amount to 2 months instead of 3.
- Changes the suggested ETH amount to 0.01 instead of 0.02.
- Fixes a bug that allowed skipping the wrapping step without having enough super token to allocate.

feat(governance): change wrap amount to 2 months of flow rate from 3

---

src/components/governance/EditStream.tsx
src/lib/utils.ts

- Adds the grantee's twitter handle in the social share copy after a successful donation.
- Remove the final slash from the link

feat(governance): add grantee twitter handle in share copy

---

package.json
src/lib/constants.ts
src/pages/Index.tsx
yarn.lock

Disables MUD syncing on mainnet and until a parcel is actually selected.

fix: do not sync MUD on mainnet or home page

---

src/components/governance/EditStream.tsx

Use the `MODE` env var to check if we are on mainnet or testnet instead of the chain ID so that the right network name is shown in the "Edit Stream" view when the user wallet is not connected.

fix(governance): network name before connecting the wallet

---

src/components/governance/EditStream.tsx
src/components/governance/MatchingPoolDetails.tsx
src/components/governance/Profile.tsx
src/components/governance/RecipientDetails.tsx
src/hooks/ethPrice.ts
src/lib/utils.ts
src/styles.scss

Add a field to the transaction details view of the donation stream flow to show the absolute QF multiplier of the user marginal change in the stream.
The ETHDAI price is fetched from Coinbase REST API, it's used to convert the matching pool amount from ETH to DAI and calculate the multiplier.

feat(governance): add QF multiplier to to transaction details view
