- src/App.js
- src/components/Map.js
- src/components/Sidebar.js
- src/components/cards/ActionForm.js
- src/components/cards/EditAction.js
- src/components/cards/ParcelInfo.js
- src/contracts/GeoWebAdmin_v0.json
Adds ability to edit the value and send additional payments for an existing license.
> Editing Existing Licenses

- src/App.js
- src/components/Map.js
- src/components/Sidebar.js
- src/components/cards/ActionForm.js
- src/components/cards/ClaimAction.js
- src/components/cards/EditAction.js
- src/components/cards/FaucetInfo.js
- src/components/cards/ParcelInfo.js
- src/components/cards/PurchaseAction.js
- src/contracts/GeoWebAdmin_v0.json
- Add force transfer parcel function
- Add the word "Additional" to "Network Fee Payment" field in Edit fuction
- The Expiration Date for an edited parcel is not being recalculated after additional fee payments
- Prepopulate sale price in the Edit Function
- Display a "Transaction Subtotal" calculated field under "New Expiration Date" in the transaction details sections of all functions.
> Purchasing existing license

- src/App.js
- src/components/cards/ActionForm.js
- src/components/cards/AuctionInfo.js
- src/components/cards/FaucetInfo.js
- src/components/cards/ParcelInfo.js
- src/constants.js
- src/contracts/GeoWebAdmin_v0.json
- src/index.js
New sidebar elements for showing auction info.
> Integrate Dutch Auction

- src/components/cards/ActionForm.js
- src/components/cards/AuctionInfo.js
- src/components/cards/ParcelInfo.js
- src/components/cards/PurchaseAction.js
- src/constants.js
- Fix expiration calculation after auction end
- Fix fee balance calculation after auction end
> Auction fixes

- src/components/cards/ParcelInfo.js
- Add time to the Expiration Date field
- Change "Licensee" truncation to show last 4 digits of wallet ID
> Expiration date time and address truncation

- src/components/FAQ.js
- src/components/cards/ActionForm.js
- src/components/cards/AuctionInfo.js
- src/components/cards/ParcelInfo.js
- src/components/cards/PurchaseAction.js
- Show proper subtotal in auction UI
- Open FAQ links in new tabs
> Auction Subtotal + FAQ Links Open in Tab

- components/Map.js
- components/Sidebar.js
- components/cards/ActionForm.js
- components/cards/ClaimAction.js
- components/cards/EditAction.js
- components/cards/ParcelInfo.js
- components/cards/PurchaseAction.js
- contracts/GeoWebAdmin_v0.json
- lib/constants.js
- pages/index.js
- Closes https://github.com/Geo-Web-Project/specs/issues/23
- Simple fields for editing the name and URI of a parcel
- Editing only the Ceramic fields on a parcel will still ask for an unneeded ETH transaction
- The root CID of a parcel can only be updated when claiming, not on purchase
> Integrate Simple Ceramic Docs

- components/cards/ParcelInfo.js
- components/cards/PurchaseAction.js
- contracts/GeoWebAdmin_v0.json
- lib/constants.js
Closes https://github.com/Geo-Web-Project/cadastre/issues/17
> Fix DocId on Purchase

- components/cards/EditAction.js
Closes https://github.com/Geo-Web-Project/cadastre/issues/16
> Only send transaction on edit if license info is changed

- components/Sidebar.js
- components/cards/ActionForm.js
- components/cards/ClaimAction.js
- components/cards/EditAction.js
- components/cards/ParcelInfo.js
- components/cards/PurchaseAction.js
- package.json
- pages/_app.js
- pages/index.js
- yarn.lock
- Closes https://github.com/Geo-Web-Project/cadastre/issues/22
- Closes https://github.com/Geo-Web-Project/cadastre/issues/21
- Migrate from Web3 to Ethers. I have been playing with the Frame wallet (another injected wallet like Metamask) and it seemed to be having issues with the Web3 provider. Not sure if this is the cause, but it now works well with Ethers.
> Minor Bug Fixes

- components/cards/ActionForm.js
- components/cards/FaucetInfo.js
- Update the transaction requirements info box copy
- Update the static warning/info message shown on the Cadastre transaction panel
> Small Cadastre Copy Updates

- components/cards/ParcelInfo.js
> Link Ceramic Stream IDs to Tiles

- components/gallery/GalleryModal.js
- lib/GeoWebBucket.js
- lib/PinningManager.js
> Handle missing pinset

- components/gallery/GalleryForm.js
> add required to File Format

- babel.config.js
- next-env.d.ts
- package.json
- pages/_app.tsx
- pages/index.tsx
- redux/store.ts
- tsconfig.json
- yarn.lock
- Closes #111
- Converts some sources into Typescript
> feat: Integrate Redux and Superfluid

- components/profile/Profile.tsx
- components/wrap/WrapModal.tsx
> fix: Profile Balance not updating

- components/cards/ActionForm.js
> fix: Claim fail on undefined content fields

- components/Map.tsx
- components/Sidebar.tsx
- components/cards/ActionForm.tsx
- components/cards/ClaimAction.tsx
- components/cards/ClaimView.tsx
- components/cards/ParcelInfo.tsx
- lib/calculateWeiSubtotalField.ts
- lib/constants.js
- lib/sfInstance.ts
- lib/stream-managers/BasicProfileStreamManager.js
- lib/utils.ts
- pages/index.tsx
- redux/store.ts
- styles.scss
> feat: added simple claim view.

- components/Map.tsx
- components/Sidebar.tsx
- components/cards/ActionForm.tsx
- components/cards/ClaimAction.tsx
- components/cards/ClaimView.tsx
- components/cards/FairLaunchInfo.tsx
- components/cards/FaucetInfo.js
- components/cards/StreamingInfo.tsx
- lib/calculateRequiredBid.ts
- package.json
- yarn.lock
> feat: added fair launch claim

- components/AuctionInstructions.tsx
- components/Map.tsx
- components/Sidebar.tsx
- components/cards/EditAction.tsx
- components/cards/FairLaunchInfo.tsx
- components/cards/OutstandingBidView.tsx
- components/cards/ParcelInfo.tsx
- components/sources/ParcelSource.tsx
> feat: Outstanding Bid View

- lib/cacao.ts
> fix: Create new cacao session on new wallet

- components/cards/StreamingInfo.tsx
- components/profile/FlowingBalance.tsx
- components/profile/Profile.tsx
- components/profile/ProfileModal.tsx
- components/wrap/WrapModal.tsx
- package.json
- pages/index.tsx
- redux/store.ts
- yarn.lock
Closes #134 
Changes the logic behind balance queries. So anywhere the ETHx balance is shown should be tested.
> chore: Update sdk-redux to 0.3.x

- components/Sidebar.tsx
- components/cards/ParcelInfo.tsx
> fix: Parcel content not shown if not owner

- components/Map.tsx
- pages/index.tsx
> fix: Switch wallet crash

- components/cards/ParcelInfo.tsx
> fix: Remove place bid button when there is an outstanding bid

- components/cards/OutstandingBidView.tsx
- components/cards/PlaceBidAction.tsx
- components/cards/RejectBidAction.tsx
> fix: Update to STATE.PARCEL_SELECTED after place, reject, and accept bid

- components/Sidebar.tsx
- components/cards/AuctionInfo.tsx
- components/cards/ClaimAction.tsx
- components/cards/FairLaunchInfo.tsx
- components/cards/ReclaimAction.tsx
- lib/utils.ts
Closes #152 
The current required bid in the `FairLaunchInfo` and  `TransactionSummaryView` cards are updated every second with the remaining time.
> Set the max claim payment to equal the required auction bid during fair launch

- components/cards/StreamingInfo.tsx
> Update streaming info card

- components/cards/TransactionSummaryView.tsx
> feat: added logic for the parcel reclaiming interation state

- components/Map.tsx
- components/Sidebar.tsx
- components/cards/ClaimAction.tsx
> fix: New land parcel claim update

- pages/index.tsx
> fix: Transactions fail if network is auto-switched

- .github/pull_request_template.md
Creating a new PR template for the Cadastre repo.
@codynhat
> docs: create a PR template

- components/Map.tsx
Dework task details: https://app.dework.xyz/bounties?taskId=80f45755-5af8-4892-b840-6aaf71e5f05e
> Save users' map preferences

- components/cards/ParcelInfo.tsx
Remove the "Unclaimed coordinates" text in the claim transaction parcel.
fixes #241 
> feat: remove unclaimed coordinates text

- components/cards/AuctionInfo.tsx
- components/cards/FairLaunchInfo.tsx
- components/cards/OutstandingBidView.tsx
- components/cards/RejectBidAction.tsx
- components/profile/ProfileModal.tsx
Use the user's local time to format the dates.
fixes #239 
> feat: show dates in local time

- components/cards/ClaimAction.tsx
- components/cards/EditAction.tsx
- components/cards/OutstandingBidView.tsx
- components/cards/PlaceBidAction.tsx
- components/cards/ReclaimAction.tsx
- components/cards/RejectBidAction.tsx
- components/cards/TransactionSummaryView.tsx
- components/profile/ProfileModal.tsx
- lib/utils.ts
- package.json
- yarn.lock
> feat: OutstandingBidView handles modified flows

- components/cards/ActionForm.tsx
- components/cards/AuctionInfo.tsx
- components/cards/PlaceBidAction.tsx
- components/cards/RejectBidAction.tsx
Update button labels for land transactions to be more descriptive.
fixes #238 
> feat: update button labels

- components/cards/ParcelInfo.tsx
- components/cards/ReclaimAction.tsx
Connect the signer to the license diamond contract.
fixes #258
> fix: add signer to reclaim contract call

- components/cards/ActionForm.tsx
- components/cards/ParcelInfo.tsx
Add section headers to action cards.
fixes #265 
> feat: add section headers to action panels

- components/Sidebar.tsx
- components/cards/ClaimAction.tsx
- components/cards/EditAction.tsx
- components/cards/OutstandingBidView.tsx
- components/cards/ParcelInfo.tsx
- components/cards/PlaceBidAction.tsx
- components/cards/ReclaimAction.tsx
- components/cards/RejectBidAction.tsx
When a new parcel is claimed refetch until the data is returned from the subgraph query.
fixes #270 
> fix: flag new parcel to update fields on claim

- components/gallery/GalleryForm.tsx
- components/gallery/GalleryModal.tsx
- lib/stream-managers/MediaGalleryItemStreamManager.ts
Update the gallery grid immediately after the user adds an item to it.
fixes #264 
> fix: show item in gallery grid after being added

- components/cards/EditAction.tsx
- components/cards/OutstandingBidView.tsx
- components/cards/ParcelInfo.tsx
- components/cards/PlaceBidAction.tsx
- components/cards/ReclaimAction.tsx
- components/cards/RejectBidAction.tsx
- lib/constants.ts
- package.json
- yarn.lock
- New Goerli deployment
- v4 contracts with minimum for sale price, new ERC721 implementation, new deployment process
- Geo Web powered Ceramic node
- No more CORS plugin!
@gravenp
> feat: New Goerli Deployment + Ceramic Node

- components/Sidebar.tsx
- components/cards/FairLaunchInfo.tsx
Change the Dutch Auction Details tooltip text to use the Dutch auction's starting and ending price.
fixes #282 
> feat: change fair launch auction tooltip copy

- components/Map.tsx
- components/cards/ClaimAction.tsx
- components/cards/StreamingInfo.tsx
- components/map-style.ts
- components/profile/Profile.tsx
- components/profile/ProfileModal.tsx
- components/sources/ParcelSource.tsx
- lib/constants.ts
- package.json
- pages/index.tsx
- yarn.lock
Uses a new subgraph index to query based on bounding box and draws a GeoJSON feature per parcel instead of drawing all coordinates. 
fixes #268 
This currently assumes all parcels are rectangles, and draws the bounding box. We should discuss next steps.
@gravenp
> feat: GeoJSON and Bounding Box Index

- package.json
> fix: Media gallery pins not working

- components/cards/ClaimAction.tsx
- components/cards/EditAction.tsx
- components/cards/PlaceBidAction.tsx
- components/cards/ReclaimAction.tsx
- components/cards/RejectBidAction.tsx
- components/cards/TransactionSummaryView.tsx
- lib/utils.ts
> fix: Stream buffer value mismatch

- components/cards/TransactionSummaryView.tsx
Display a plus sign for positive changes in *Stream* and *Stream Buffer* values in *Transaction Summary* view.
fixes #261 
> feat: show a plus sign for positive stream delta changes

- components/wrap/WrapModal.tsx
Update WrapModal component by changing the submit button size and the formatting of the user's balances to 8 decimal places.
fixes #296 
> feat: change button size and balance formatting in WrapModal

- components/ApproveButton.tsx
When a user approve a stream or a transfer only allow the amount of ETHx required for the transaction to complete.
If *For Sale Price* change after the user allowed a transaction a new approval must be granted.
fixes #312 
> feat: authorize only up to the required amounts for flows and transfers

- .gitignore
- components/cards/ClaimAction.tsx
- components/cards/EditAction.tsx
- components/cards/OutstandingBidView.tsx
- components/cards/ParcelInfo.tsx
- components/cards/PlaceBidAction.tsx
- components/cards/ReclaimAction.tsx
- components/cards/RejectBidAction.tsx
- flake.lock
- flake.nix
- package.json
- yarn.lock
Updates the SDK to the latest version, which has some redesign and breaking changes. Also adds a Nix Flake dev shell for anyone else using Nix.
@tnrdd
> chore: Update SDK

- components/cards/ActionForm.tsx
- components/cards/ClaimAction.tsx
- components/cards/PlaceBidAction.tsx
- components/cards/RejectBidAction.tsx
- lib/superTokenBalance.ts
Show a warning message when the user's ETHx balance in less than the amount required to complete a transaction.
fixes #318 
> feat: add ETHx balance validation

- components/Home.tsx
Comment out Beta Agreement modal until launch.
fixes #329 
> feat: comment out beta agreement modal

- components/cards/PlaceBidAction.tsx
- components/cards/RejectBidAction.tsx
> chore: Remove transaction info/warning section

- package.json
- yarn.lock
Bump ethers.js version to 5.7.2
fixes #348 
> build: bump ethers to 5.7.2

- lib/calculateRequiredBid.ts
> fix: Incorrect fair launch auction price calculation

- components/cards/FairLaunchInfo.tsx
This reverts commit f6bf41ebb00a5e0ca33f6908fbffc93f32b4f099.
fixes #ISSUE
@gravenp
> chore: Revert Dutch auction email notification modal (#346)

- components/gallery/GalleryDisplayItem.tsx
- package.json
- yarn.lock
> fix: Pin on delete from media gallery

- components/gallery/GalleryFileFormat.ts
- components/gallery/GalleryForm.tsx
- components/gallery/GalleryModal.tsx
- pages/index.tsx
Add support for uploading images in the media gallery modal.
fixes #380 
> feat: add support for image uploads in the media gallery

- package.json
- yarn.lock
Fixes an issue where IPFS gateway calls were not being performed if root could not be resolved.
> fix: Update @geo-web/content to 0.5.3

- .env.mainnet
- .env.testnet
- lib/constants.ts
- pages/index.tsx
Use Geo Web IPFS node as the delegate instead of the soon-to-be-deprecated ipfs.io nodes. This may improve fetch performance, since the Geo Web nodes are peered with Web3.storage nodes.
> perf: Use Geo Web run delegate node

- components/cards/ParcelInfo.tsx
Lazy load chat modal to reduce first load JS bundle size by ~35%.
> perf: lazy load chat module

- components/cards/ClaimAction.tsx
This adds some simple error handling to claim referrals. Each referral is stored in local storage and cleared upon successful acknowledgment from the server. If the call to the server fails for whatever reason, the referral will be sent again on the next claim.
@tnrdd @0xtekgrinder
> fix: Handle errors on claim referral

- components/FAQ.tsx
- components/Home.tsx
- components/WelcomeChecklist.tsx
- components/nav/NavMenu.tsx
- pages/index.tsx
Change the modal shown on first visit and update the FAQs.
fixes #429 
> feat: change welcome modal

- components/profile/AddFundsModal.tsx
- components/profile/ProfileModal.tsx
> feat: External Fiat Onramp

- components/FAQ.tsx
- components/WelcomeChecklist.tsx
- components/nav/NavMenu.tsx
- package.json
- pages/_app.tsx
- yarn.lock
> chore: update RainbowKit to 0.12.15+ and WalletConnect v2

- src/components/governance/EditStream.tsx
> feat(governance): change DAI on ramp to DAIx

- src/components/governance/Profile.tsx
- src/components/shared/NavMenu.tsx
- src/styles.scss
- Adds the yellow color to the stylesheet
- Aligns the "Buy ETH" text in the header's menu
> fix: missing color var in stylesheet

- src/components/shared/FundsRaisedCounter.tsx
Uses the total amount streamed in plus the total amount transferred from the beneficiary address and the total inflow rate for the counter of the funds raised in the header.
> fix: use inflow rate only for the header counter

- src/components/governance/Profile.tsx
- src/components/shared/FundsRaisedCounter.tsx
- src/components/shared/NavMenu.tsx
- src/styles.scss
> Merge develop into main

- src/components/shared/FundsRaisedCounter.tsx
- src/components/shared/Header.tsx
Center the position of the funds raised counter in the header.
> fix: header counter position

- src/components/governance/EditStream.tsx
Update the Warpcast ID of Superfluid in the social share link in the governance page.
> feat(governance): update warpcast handle of superfluid

- src/pages/Governance.tsx
- src/redux/store.ts
Update subgraph URLs to use Superfluid dedicated endpoints
> perf(governance): use superfluid subgraph dedicated endpoint

- .env.mainnet
- .env.testnet
- global.d.ts
- index.html
- src/components/cadastre/ApproveButton.tsx
- src/components/cadastre/Map.tsx
- src/components/cadastre/PerformButton.tsx
- src/components/cadastre/cards/ActionForm.tsx
- src/components/governance/EditStream.tsx
- src/components/shared/ConnectWallet.tsx
- src/hooks/analyticsEvent.ts
Add web analytics with events for:
- Connect Wallet
- Start a Claim
- Confirm Shape
- ETHx Allowance Button
- Submit Claim Button
- Successful Claim
- Fund Matching Pool - Step 1
- Fund Matching Pool - Step 2
- Fund Matching Pool - Step 3
- Fund Matching Pool - Step 4
- Fund Matching Pool - Success
- Fund Grantee - Step 1
- Fund Grantee - Step 2
- Fund Grantee - Step 3
- Fund Grantee - Step 4
- Fund Grantee - Step 5
- Fund Grantee - Success
> feat: add web analytics

- src/components/governance/EditStream.tsx
After a successful transaction and while waiting for confirmations the data from the subgraph could update before the "Success" view resulting in the transaction details view not showing anymore the info from the transaction the user submitted.
This fixes it by keeping a transaction details snapshot taken at submission time and showing the info from that during transactions execution.
> fix(governance): do not update review step details before success view

- src/components/governance/EditStream.tsx
- src/components/governance/FundGrantee.tsx
- src/components/governance/FundMatchingPool.tsx
- src/hooks/superfluid.ts
Batch wrap, update permissions and create/update/delete flow operations in the grantee donation flow.
> feat(governance): batch Superfluid calls

- src/components/governance/EditStream.tsx
- src/components/governance/FundGrantee.tsx
- src/components/governance/FundMatchingPool.tsx
- src/hooks/superfluid.ts
Please provide a detailed description of what was done in this PR
fixes #ISSUE
> feat(governance): batch Superfluid calls (#505)

- src/components/governance/StreamingQuadraticFunding.tsx
- src/hooks/roundQuery.ts
Updates the subtitle of the governance page.
> feat(governance): update subheader

- .env.mainnet
- .env.testnet
- package.json
- src/context/Allo.tsx
- src/hooks/geo-web-content/basicProfile.ts
- src/lib/constants.ts
- src/lib/utils.ts
- yarn.lock
Use `@helia/verified-fetch` to fetch IPFS content with six gateways fallback.
fixes #511 
> perf: use IPFS fetching lib

- index.html
- src/components/cadastre/Map.tsx
- src/components/shared/Header.tsx
- src/styles.scss
> feat: remove intercom widget

- index.html
- src/components/cadastre/Map.tsx
- src/components/shared/Header.tsx
- src/styles.scss
* feat: remove intercom widget
* fix: map controls position
Please provide a detailed description of what was done in this PR
fixes #ISSUE
> feat: remove intercom widget (#513)

- src/redux/store.ts
Update Superfluid subgraph endpoint
> feat: update Superfluid subgraph endpoint

- src/redux/store.ts
Please provide a detailed description of what was done in this PR
fixes #ISSUE
> feat: update Superfluid subgraph endpoint (#515)
